server:
  port: 8004
spring:
  profiles:
    active: dev
  application:
    name: cloud-wish-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3307/summer_training?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.sheep.cloud.entity    # 所有Entity别名类所在包
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: wish-service-8004
#    prefer-ip-address: true